module.exports = {
  plugins: [
    require("@tailwindcss/postcss")({
      content: ["./src/**/*.{html,js,ts,jsx,tsx}", "./public/index.html"],
      safelist: [
        // background colors
        "bg-white",
        "bg-black",
        "bg-gray-100",
        "bg-gray-200",
        "bg-gray-300",
        "bg-gray-400",
        "bg-gray-500",
        "bg-red-500",
        "bg-green-500",
        "bg-blue-500",
        "bg-yellow-500",
        "bg-indigo-500",
        "bg-purple-500",
        "bg-pink-500",

        // text colors
        "text-white",
        "text-black",
        "text-gray-500",
        "text-red-500",
        "text-green-500",
        "text-blue-500",
        "text-yellow-500",
        "text-indigo-500",
        "text-purple-500",
        "text-pink-500",
        "text-green-600",
        "text-orange-500",

        "text-[2px]",
        "text-[3px]",
        "text-[4px]",
        "text-[5px]",
        "text-[6px]",
        "text-[7px]",
        "text-[8px]",
        "text-[9px]",
        "text-[10px]",
        "text-[11px]",
        "text-[12px]",
        "text-[13px]",
        "text-[14px]",
        "text-[15px]",
        "text-[16px]",

        "animate-none",
        "animate-spin",
        "animate-ping",
        "animate-pulse",
        "animate-bounce",

        "border-r",
        "border-r-0",
        "border-r-2",
        "border-r-4",
        "border-r-8",

        // border-left
        "border-l",
        "border-l-0",
        "border-l-2",
        "border-l-4",
        "border-l-8",

        // border-top
        "border-t",
        "border-t-0",
        "border-t-2",
        "border-t-4",
        "border-t-8",

        // border-right colors
        "border-r-white",
        "border-r-black",
        "border-r-gray-500",
        "border-r-red-500",
        "border-r-green-500",
        "border-r-blue-500",
        "border-r-yellow-500",
        "border-r-indigo-500",
        "border-r-purple-500",
        "border-r-pink-500",
        "bg-green-200",
        "bg-green-300",
        "hover:text-red-500",
        "text-gray-400",
        "hover:bg-white/10",
        "rounded-full",
        "transition",
        "text-xs",
        "hover:bg-gray-700",
        "opacity-70",
        "w-4",
        "h-4",
        "w-6",
        "h-6",
        "flex",
        "items-center",
        "justify-center",
        "ml-auto",
        "relative",
        "cursor-pointer",
        "z-10",

        // border-left colors
        "border-l-white",
        "border-l-black",
        "border-l-gray-500",
        "border-l-red-500",
        "border-l-green-500",
        "border-l-blue-500",
        "border-l-yellow-500",
        "border-l-indigo-500",
        "border-l-purple-500",
        "border-l-pink-500",

        // border-top colors
        "border-t-white",
        "border-t-black",
        "border-t-gray-500",
        "border-t-red-500",
        "border-t-green-500",
        "border-t-blue-500",
        "border-t-yellow-500",
        "border-t-indigo-500",
        "border-t-purple-500",
        "border-t-pink-500",

        // font sizes
        "text-xs",
        "text-sm",
        "text-base",
        "text-lg",
        "text-xl",
        "text-2xl",
        "text-3xl",
        "text-4xl",
        "text-5xl",
        "text-6xl",

        // font families
        "font-sans",
        "font-serif",
        "font-mono",

        // paddings
        "pt-1",
        "pt-2",
        "pt-4",
        "pt-8",
        "pt-16",
        "pb-1",
        "pb-2",
        "pb-4",
        "pb-8",
        "pb-16",
        "pl-1",
        "pl-2",
        "pl-4",
        "pl-8",
        "pl-16",
        "pr-1",
        "pr-2",
        "pr-4",
        "pr-8",
        "pr-16",
        "px-1",
        "px-2",
        "px-4",
        "px-8",
        "px-16",
        "py-1",
        "py-2",
        "py-4",
        "py-8",
        "py-16",

        // bg-opacity
        "bg-opacity-0",
        "bg-opacity-5",
        "bg-opacity-10",
        "bg-opacity-20",
        "bg-opacity-25",
        "bg-opacity-30",
        "bg-opacity-40",
        "bg-opacity-50",
        "bg-opacity-60",
        "bg-opacity-70",
        "bg-opacity-75",
        "bg-opacity-80",
        "bg-opacity-90",
        "bg-opacity-95",
        "bg-opacity-100",

        // utility & animation
        "bottom-0",
        "bottom-5",
        "bottom-10",
        "left-1/2",
        "transform",
        "-translate-x-1/2",
        "animate-typing",
        "overflow-hidden",
        "whitespace-nowrap",
        "border-r-4",
        "border-r-white",
        "border-gray-200",
        "border-gray-300",
        "border-gray-400",
        "border-gray-500",
        "border",
        "border-0",
        "border-2",
        "border-4",
        "border-8",
        "border-t",
        "border-r",
        "border-b",
        "border-l",
        "border-t-0",
        "border-r-0",
        "border-b-0",
        "border-l-0",
        "border-t-2",
        "border-r-2",
        "border-b-2",
        "border-l-2",
        "border-t-4",
        "border-r-4",
        "border-b-4",
        "border-l-4",
        "border-t-8",
        "border-r-8",
        "border-b-8",
        "border-l-8",
        "pr-5",
        "text-5xl",
        "font-bold",

        // margins
        "m-0",
        "m-1",
        "m-2",
        "m-4",
        "m-8",
        "m-16",
        "mt-0",
        "mt-1",
        "mt-2",
        "mt-4",
        "mt-8",
        "mt-16",
        "mb-0",
        "mb-1",
        "mb-2",
        "mb-4",
        "mb-8",
        "mb-16",
        "ml-0",
        "ml-1",
        "ml-2",
        "ml-4",
        "ml-8",
        "ml-16",
        "mr-0",
        "mr-1",
        "mr-2",
        "mr-4",
        "mr-8",
        "mr-16",
        "mx-0",
        "mx-1",
        "mx-2",
        "mx-4",
        "mx-8",
        "mx-16",
        "my-0",
        "my-1",
        "my-2",
        "my-4",
        "my-8",
        "my-16",

        // right position
        "right-0",
        "right-1",
        "right-2",
        "left-3",
        "right-4",
        "right-8",
        "right-16",

        // notification badge
        // Width classes
        "w-0",
        "w-0.5",
        "w-1",
        "w-1.5",
        "w-2",
        "w-2.5",
        "w-3",
        "w-3.5",
        "w-4",
        "w-5",
        "w-6",
        "w-7",
        "w-8",
        "w-9",
        "w-10",
        "w-11",
        "w-12",
        "w-14",
        "w-16",
        "w-20",
        "w-24",
        "w-28",
        "w-32",
        "w-36",
        "w-40",
        "w-44",
        "w-48",
        "w-52",
        "w-56",
        "w-60",
        "w-64",
        "w-72",
        "w-80",
        "w-96",
        "h-3/4",
        "h-4/5",
        "w-auto",
        "w-px",
        "w-full",
        "w-screen",
        "w-min",
        "w-max",
        "w-fit",
        "max-h-screen",
        "overflow-y-auto",

        // Height classes
        "h-0",
        "h-0.5",
        "h-1",
        "h-1.5",
        "h-2",
        "h-2.5",
        "h-3",
        "h-3.5",
        "h-4",
        "h-5",
        "h-6",
        "h-7",
        "h-8",
        "h-9",
        "h-10",
        "h-11",
        "h-12",
        "h-14",
        "h-16",
        "h-20",
        "h-24",
        "h-28",
        "h-32",
        "h-36",
        "h-40",
        "h-44",
        "h-48",
        "h-52",
        "h-56",
        "h-60",
        "h-64",
        "h-72",
        "h-80",
        "h-96",
        "h-auto",
        "h-px",
        "h-full",
        "h-screen",
        "h-min",
        "min-h-screen",
        "h-[calc(100vh-4rem)]",
        "h-max",
        "h-fit",
        "border-2",
        "border-white",
        "rounded-full",
        "justify-end",
        "justify-start",
        "bg-blue-500",
        "bg-gray-100",
        "text-white",
        "text-gray-900",
        "rounded-br-none",
        "rounded-bl-none",
        "rounded-2xl",
        "text-sm",
        "text-[10px]",
        "opacity-60",
        "flex-col-reverse",
        "space-y-reverse",
        "space-y-2",
        "break-all",
        "break-words",
        "cursor-not-allowed",
        "ease-in-out",

        // позиционирование
        "inset-0",
        "inset-x-0",
        "inset-x-1",
        "inset-x-2",
        "inset-x-4",
        "inset-x-8",
        "inset-x-16",
        "inset-y-0",
        "inset-y-1",
        "inset-y-2",
        "inset-y-4",
        "inset-y-8",
        "inset-y-16",
        "absolute",
        "relative",
        "inset-0",
        "inset-y-1",
        "inset-y-2",
        "top-0",
        "left-0",
        "right-0",
        "bottom-0",
        "z-0",
        "z-10",
        "z-20",

        // Size
        "w-full",
        "h-full",

        // Overflow & pointer events
        "pointer-events-none",
        "overflow-hidden",

        // Background & gradient
        "bg-gradient-to-r",
        "from-transparent",
        "via-yellow-400/30",
        "to-transparent",

        // Animation
        "animate-typing",
        "animate-scrollLeft",
        "animate-shimmer",

        // Custom shimmer class
        "chat-shimmer",

        // Display
        "block",
        "hidden",

        // Others (if used)
        "rounded",
        "rounded-md",
        "rounded-lg",
        "opacity-0",
        "opacity-50",
        "opacity-100",
        "transition-opacity",
        "duration-1000",
        "ease-out",

        "top-0",
        "top-1",
        "top-2",
        "top-4",
        "top-8",
        "top-16",

        "bottom-0",
        "bottom-1",
        "bottom-2",
        "bottom-4",
        "bottom-8",
        "bottom-16",

        "left-0",
        "left-1",
        "left-2",
        "left-4",
        "left-8",
        "left-16",

        "right-0",
        "right-1",
        "right-2",
        "right-3",
        "right-4",
        "right-8",
        "right-16",

        // отрицательные значения (если вдруг нужно)
        "-top-1",
        "-top-2",
        "-top-4",
        "-right-1",
        "-right-2",
        "-right-4",
        "-bottom-1",
        "-bottom-2",
        "-bottom-4",
        "-left-1",
        "-left-2",
        "-left-4",

        // трансформации (если используешь translate и transform)
        "translate-x-1/2",
        "-translate-x-1/2",
        "translate-y-1/2",
        "-translate-y-1/2",
        "top-1/2",
        "transform",
      ],
      plugins: [],
    }),
    require("autoprefixer"),
  ],
};
