module.exports = {
  plugins: [
    require("@tailwindcss/postcss")({
      content: ["./src/**/*.{html,js,ts,jsx,tsx}", "./public/index.html"],
      safelist: [
        // background colors
        "bg-white",
        "bg-black",
        "bg-gray-100",
        "bg-gray-200",
        "bg-gray-500",
        "bg-red-500",
        "bg-green-500",
        "bg-blue-500",
        "bg-yellow-500",
        "bg-indigo-500",
        "bg-purple-500",
        "bg-pink-500",

        // text colors
        "text-white",
        "text-black",
        "text-gray-500",
        "text-red-500",
        "text-green-500",
        "text-blue-500",
        "text-yellow-500",
        "text-indigo-500",
        "text-purple-500",
        "text-pink-500",

        // font sizes
        "text-xs",
        "text-sm",
        "text-base",
        "text-lg",
        "text-xl",
        "text-2xl",
        "text-3xl",
        "text-4xl",
        "text-5xl",
        "text-6xl",

        // font families
        "font-sans",
        "font-serif",
        "font-mono",

        // paddings
        "pt-1",
        "pt-2",
        "pt-4",
        "pt-8",
        "pt-16",
        "pb-1",
        "pb-2",
        "pb-4",
        "pb-8",
        "pb-16",
        "pl-1",
        "pl-2",
        "pl-4",
        "pl-8",
        "pl-16",
        "pr-1",
        "pr-2",
        "pr-4",
        "pr-8",
        "pr-16",
        "px-1",
        "px-2",
        "px-4",
        "px-8",
        "px-16",
        "py-1",
        "py-2",
        "py-4",
        "py-8",
        "py-16",

        // bg-opacity
        "bg-opacity-0",
        "bg-opacity-5",
        "bg-opacity-10",
        "bg-opacity-20",
        "bg-opacity-25",
        "bg-opacity-30",
        "bg-opacity-40",
        "bg-opacity-50",
        "bg-opacity-60",
        "bg-opacity-70",
        "bg-opacity-75",
        "bg-opacity-80",
        "bg-opacity-90",
        "bg-opacity-95",
        "bg-opacity-100",

        // utility & animation
        "bottom-0",
        "bottom-5",
        "bottom-10",
        "left-1/2",
        "transform",
        "-translate-x-1/2",
        "animate-typing",
        "overflow-hidden",
        "whitespace-nowrap",
        "border-r-4",
        "border-r-white",
        "pr-5",
        "text-5xl",
        "font-bold",
      ],
      plugins: [],
    }),
    require("autoprefixer"),
  ],
};
