version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendenc_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/db/database.sqlite:/app/database.sqlite
      # Не монтируем node_modules
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/database.sqlite
    restart: unless-stopped
    command: sh -c "chmod 666 /app/database.sqlite && node src/index.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendenc_frontend
    ports:
      - "8888:8888"
    volumes:
      - ./frontend:/app
      # Не монтируем node_modules
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend