version: "3.8"

services:
  sqlite:
    image: alpine
    container_name: sqlite_container
    volumes:
      - ./backend/db:/data
    command: [ "sh", "-c", "apk add --no-cache sqlite && tail -f /dev/null" ]
