services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendenc_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/db:/app/db
    environment:
      - NODE_ENV=development
    command: sh -c "mkdir -p /app/db && touch /app/db/database.sqlite && node src/index.js"  
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendenc_frontend
    ports:
      - "8888:8888"
    volumes:
      # - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend