services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transcendenc_backend
    ports:
      - "3000:3000"
      - "9229:9229"  # Порт для отладчика
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/db:/app/db
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && node --inspect=0.0.0.0:9229 src/index.js"  
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendenc_frontend
    ports:
      - "8888:8888"
    volumes:
      # - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend